### ISSUE TITLE
stale `useProp` values when passing data from parent to child

### ISSUE THREAD

**Issue by WickyNilliams** [atomicojs/atomico#126]
**Describe the bug**
I noticed that in a parent-child relationship, where the child accesses a prop via `useProp`, the prop's value can become stale/out of date.

**Browser (please complete the following information):**
 - Browser: any
 - Version: n/a

**To Reproduce**
1. Go to https://stackblitz.com/edit/atomico-use-prop-stale?file=src%2Ftest.tsx
2. Click on the plus button
4. Notice that the `useProp` value does not update in the child, whilst it does in every other place

**Screenshots or video**

**Expected behavior**
The value returned from `useProp` should always match the value from the props arg passed to the component function

**Comment by UpperCod** [comment]
Ready 👍, bug fixed in atomico@1.76.1, Thanks for sharing your issue

**Comment by WickyNilliams** [comment]
Confirmed the issue is resolved in the stackblitz above. Thanks again!
