### ISSUE TITLE
Unable to install any version after 1.70.0

### ISSUE THREAD

**Issue by is-jonreeves** [atomicojs/atomico#127]
**Describe the bug**
Was revisiting Atomico today and ran into an error while running `npm i` after `npm init @atomico`. 

**System**
- Windows 10
- Node 20

**To Reproduce**
1. `npm init @atomico`
2. `npm i`

or

1. `npm i atomico@latest`

or

1. `npm i -D @atomico/vite`

**Error**
```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Expected behavior**
No errors during installation

**Additional context**
I tried removing the `node_modules/` and starting again a few times. There is no package-lock generated yet (because of the failures). I also tried installing each package manually and the only two that wouldn't install were; `atomico` and `@atomico/vite`.

I created a new, empty project and attempted to install atomico there and it failed too. I tried various older versions, and was able to successfully install `1.70.0` but nothing afterwards, i.e... `npm i atomico@1.71.0` fails.

**Comment by UpperCod** [comment]
Thanks for sharing this issue, as it's crucial to fix it . In summary:
In node@20, an error was generated when trying to move the .github and .vscode folders that were included in Atomico as a package. In version [atomico@1.76.3](https://github.com/atomicojs/atomico/releases/tag/1.76.3), we have fixed these folders and files in the package ✅.

**Comment by is-jonreeves** [comment]
Thanks for the quick response and fix. I just tried out the new release and am up and running now!
