### ISSUE TITLE
Typings is missing?

### ISSUE THREAD

**Issue by lostfields** [atomicojs/atomico#18]
Hi, I was going to start using this lib with a typescript project, still trying it out to see if it works - but I noticed that typings is missing after installing it with npm?

I've made a red circle around the file that is missing

![image](https://user-images.githubusercontent.com/4351799/69484156-21697580-0e30-11ea-9f3e-2411035c53e3.png)

**Comment by UpperCod** [comment]
Hi, thanks for your issue, I have corrected this in version 0.14.3, I'm not a TS user, so I would appreciate if you have any comments on the statements I have generated for Atomico. [index.d.ts](https://github.com/atomicojs/atomico/blob/master/index.d.ts)

**Comment by lostfields** [comment]
> Hi, thanks for your issue, I have corrected this in version 0.14.3, I'm not a TS user, so I would appreciate if you have any comments on the statements I have generated for Atomico. [index.d.ts](https://github.com/atomicojs/atomico/blob/master/index.d.ts)

Sure thing, I've noticed a few things and I can update them to make them even better.
