### ISSUE TITLE
Code that never execute

### ISSUE THREAD

**Issue by A-owl** [atomicojs/atomico#21]
https://github.com/atomicojs/atomico/blob/master/src/core/element/element.js#L171

```
customElements.define(
  nodeType,
  component instanceof Element ? component : customElement(component)
);
```

`component instanceof Element` never will be true.  `component` is a constructor , not a instance.

suggest:
```
customElements.define(
  nodeType,
  customElement(component)
);
```

**Comment by UpperCod** [comment]
Thanks for the observation and contribution, I generated the change in version 0.15.1 and added some additional comments to the code for better reading
https://github.com/atomicojs/atomico/blob/master/src/core/element/element.js#L169
