### ISSUE TITLE
npm package version 0.15.4, but repository is 0.15.3

### ISSUE THREAD

**Issue by dy** [atomicojs/atomico#22]
Is there a source code discrepancy?

**Comment by UpperCod** [comment]
I apologize, now it's solved, version 0.15.4 improves the experience of web-components that extend existing elements, eg.

```jsx
import { h, customElement } from "atomico";

function MyButton() {
  return <host>custom button</host>;
}

export default customElement("my-button", MyButton, {
  base: HTMLButtonElement,
  extends: "button"
});

// import

import MyButton from "./my-button";

console.log(<MyButton></MyButton>); // <button is="my-button"></button>
```
 The idea of importing the module and using it as jsx is to reference its origin, this is beneficial for tree-shaking and debug
