### ISSUE TITLE
Readme example is broken - simple web-components don't work

### ISSUE THREAD

**Issue by dy** [atomicojs/atomico#23]
[Sandbox](https://codesandbox.io/s/heuristic-nash-so42c?fontsize=14&hidenavigation=1&theme=dark)

```js
import { h, customElement } from "atomico";

function MyCustomButton() {
  console.log("atomico");
  return (
    <host>
      <button>Atomico custom button</button>
    </host>
  );
}

let btnClass = customElement(MyCustomButton);

// atomico button - fails
customElements.define("custom-btn-atomico", btnClass);
let btnA = document.createElement("custom-btn-atomico");
document.body.appendChild(btnA);
```

This component is never triggered.

**Comment by dy** [comment]
Something's up with codesandbox. Using atomico as cdn dep seems to work fine.

**Comment by UpperCod** [comment]
Hi, Your code is fine, but the problem has to do with the configuration of the sandbox
eg https://codesandbox.io/s/atomico-base-fnq8h

**Comment by dy** [comment]
What's the config? That seems to be the case for _haunted_ as well.
