### ISSUE TITLE
Usage without JSX?

### ISSUE THREAD

**Issue by kristianmandrup** [atomicojs/atomico#26]
I would like to create Atomico bindings for the [Nim language](https://nim-lang.org/) which does not have JSX support built in. What are the equivalent function calls? Thanks. 
I believe I can perhaps call `h`. Could you make a small example (perhaps in the Readme or docs) for how to write the equivalent of:

```html
<host shadowDom style={{background: 'black'}}>{message}</host>
```

I would think it follows the same API as used by [mithril](https://mithril.js.org/index.html#dom-elements)

```js
h('host', {shadowDom: true, style: {background: 'black'}}, message)
```

Ah, I see there is a [section on VDom](https://atomico.gitbook.io/doc/guides/virtual-dom) in the docs, but not entirely clear if I can use the `h` function as is typical with VDom. Please provide more examples, including `host` with and without `shadowDom` attribute enabled.

I see this syntax:

```js
{
    nodeType : "host",
    children : [{
        nodeType : "button",
        onclick : handler
    }]
}
```

But would assume that `h` can be used to generate this under the hood?
Please advice. Thanks.

Well I guess I can just use the `html` function with string interpolation:

```nim
html("""
<host shadowDom style="background: ${backgroundColor}>
  ${message}
</host>
""'
```

**Comment by UpperCod** [comment]
Hi, if like mithril, hyperapp or preact, you can call `h` to create the virtual-dom. Thank you for your observation I have updated the documentation following your issue.

https://atomico.gitbook.io/doc/guides/virtual-dom

>"But would assume that h can be used to generate this under the hood?"

if atomico uses this function to generate the virtual-dom and is also used by the [html](https://github.com/atomicojs/atomico/blob/master/src/html.js) function

I hope you find it useful, I remain attentive to your experience with atomico + nim-lang 👀
