### ISSUE TITLE
Bad experience on first try for beginner

### ISSUE THREAD

**Issue by ryuran** [atomicojs/atomico#31]
# Hello

At first I was seduced by the documentation.
So It tried it and I will tell you my adventure.

## At first the documentation

In the readme.md I tried "My first component" link but it's 404 : https://atomico.gitbook.io/doc/get-started/quick-start

Nothing important there is a link to the documentation with the ["instalation page"](https://atomico.gitbook.io/doc/get-started/installation).

### First try
I run `npm init @atomico` in my directory.
It ask me the directory to install it, I let it empty because I want it in the current directory.
It's done !
…or not
<img width="406" alt="Screenshot 2020-04-25 at 11 51 23" src="https://user-images.githubusercontent.com/1309340/80276789-2dad7380-86eb-11ea-8d22-577db6a3a0cb.png">

Ok maybe "empty" is not a good answer but why the message seems notice a success if it's not.
I notice the strange `1. cd ./`

### Second try

I run `npm init @atomico` in my directory.
It ask me the directory to install it, I answer to the prompt with `.` because I want it in the current directory.
And It works.
<img width="904" alt="Screenshot 2020-04-25 at 11 59 45" src="https://user-images.githubusercontent.com/1309340/80276988-52eeb180-86ec-11ea-9267-f134b7ff34ac.png">

I notice again the strange `1. cd ./.`

### First try

As the cli said I run ~~`cd ./.`~~ `npm install` and everything seems OK.

Then `npm run dev` : 
<img width="550" alt="Screenshot 2020-04-25 at 12 04 58" src="https://user-images.githubusercontent.com/1309340/80277096-05267900-86ed-11ea-8f50-16488d3a4aeb.png">

I'm not able to `Enjoy Atomico!` as the cli said.

### Second try
So I go to the `package.json` to look at the scripts entry.
`dev` do not exist but `start` is here.

So I run `npm start` and it works :
<img width="628" alt="Screenshot 2020-04-25 at 12 07 37" src="https://user-images.githubusercontent.com/1309340/80277156-68181000-86ed-11ea-80c0-7ccd36da0134.png">

Or not, http://localhost:8000/ display only `Not Found`…
And a new directory is created `src/**/*.html/` with some content…

By reading this script I was expected to see this content in `./docs`
```
"start": "bundle src/**/*.{md,html} docs --watch --server --template template/theme/theme.html",
```

Finally I stopped to try. I sadly lost my faith in atomico.js

**Comment by UpperCod** [comment]
Hi @ryuran , I apologize for the initial experience with Atomico, to correct this I have generated improvements and fixes by using the command `npm init @atomico`:

1. Now the `npm init @ atomico` command runs 90% faster.

2. The error to use the concurrent folder of the terminal is solved.

3. Now a display of different types of projects is shown to facilitate from initial to advanced use, eg:

```bash
>npm init @atomico
npx: instaló 2 en 1.636s

Welcome to Atomico, let's create your project

√ Project destination folder? ... ./
? Select the type of project » - Use arrow-keys. Return to submit.
>   Getting started with Atomico - Blazing fast as Parceljs but for webcomponents, zero configuration
    Getting started with Atomico + Snowpack
    Create Design System with Atomico

```
4. Fixed the message from  ` npm run dev` to `npm start`

Your feedback has been very useful to achieve these modifications, I hope this motivates you to try Atomico again
