### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by vogloblinsky** [atomicojs/Atomico#5]
Hi,

I have created a benchmark suite for Web Components librairies. Atomico is implemented, and you can see the raw results here : https://vogloblinsky.github.io/web-components-benchmark/

I will release soon a blog post explaining in detail that, but i want a feedback of many librairies authors before, to be sure i am not wrong in my implementations.

Source code here : https://github.com/vogloblinsky/web-components-benchmark

Can you have a look and give me some feedbacks ?

Thanks

**Comment by UpperCod** [comment]
Hi, thank you very much generate this benchmark , is well implemented, but unfortunately I will abandon Atomico as a project, I have not satisfied the use of Atomico in real projects, that if I will contribute to your repository with my new project [orby](https://github.com/orbyjs/core). this one has a maturation of the diff process of Atomico and focuses on the generation of functional components, soon premiere orby/tag that would look for the same as skatejs

**Comment by vogloblinsky** [comment]
Ok no problem. I will follow you work on Orby, feel free to implement it in this benchmark if you want.
Regards
