### ISSUE TITLE
UNPKG error: `Cannot find "/index.js" in atomico@1.30.2`

### ISSUE THREAD

**Issue by Explosion-Scratch** [atomicojs/atomico#54]
`index.js` does not exist. Perhaps this is built somehow? Anyways, is there an alternate way to use atomico in the browser?

**Comment by UpperCod** [comment]
Hi Atomico works on any CDN that supports ESM, example:
1. `unpkg.com/atomico/core` : now in unpkg you should add the prefix `core`, **I will correct this in the next version.**
2. esm.sh/atomico
3. cdn.skypack.dev/atomico

to use Atomico in the browser you only need the import, example:

```js
import { c, html, css } from "https://cdn.skypack.dev/atomico";

function component(){
  return html`<host shadowDom>
    <h1>Atomic in browser</h1>    
  </host>`;
}

component.styles = css`
  :host{
    font-family: monospace;
    color: crimson;
  }
`

customElements.define("my-component",c(component));
```
[livecode](https://codepen.io/uppchile/pen/XWgryje)

by the way you can start with Atomico using the command `npm init @atomico` or cloning this repo https://github.com/atomicojs/base, I invite you to join [Discord](https://t.co/GOwj7XKrvy?amp=1)

**Comment by Explosion-Scratch** [comment]
Thanks! Super excited to use this!
