### ISSUE TITLE
Getting started tutorial?

### ISSUE THREAD

**Issue by Explosion-Scratch** [atomicojs/atomico#55]
It seems like almost every major library has this as one of the main pages in their documentation. I think that it would be really great to have a basic tutorial for how to use atomico in the browser, along with some codepen examples. Perhaps something like a todo list app would be good? I think that this tutorial should be oriented towards complete beginners and give a general overview of the library's main functions.

(also, I realize I created two issues today, sorry if that's an annoying thing to do =| )

**Comment by UpperCod** [comment]
Working on it, by the way a while ago I created some videos that could help you get started  https://www.youtube.com/channel/UCDuCiVASTng8r4jN6BkuNVg

**Comment by Explosion-Scratch** [comment]
Sounds great!
