### ISSUE TITLE
(Suggestion) Use XHTM instead of HTM for HTML parsing

### ISSUE THREAD

**Issue by lokimckay** [atomicojs/atomico#63]
## Example repo

https://github.com/lokimckay-references/atomico-html2jsx

![Screenshot 2021-10-26 011725](https://user-images.githubusercontent.com/14341953/138725309-46167646-e70c-481d-a1cd-30f5391d00b1.png)

## Motivation

As an atomico user, I want to grab regular HTML elements from the "light DOM" and render them in my web component
(including HTML5 void elements)

According to [the docs](https://atomico.gitbook.io/doc/), the way to do that is like this:
```jsx
import { c, html } from "https://unpkg.com/atomico";

function component({ name }) {
  return html`<host shadowDom>Hello, ${name}</host>`;
}
...
```

..but [atomico uses "htm"](https://github.com/atomicojs/atomico/blob/master/html/html.js#L1) ([htm](https://github.com/developit/htm)) which is not intended to be an HTML parser, and [does not support HTML5 void elements](https://github.com/developit/htm/issues/171#issuecomment-696352952)

As a result of this, the following snippet will not work in atomico:

```jsx
import { c, html } from "https://unpkg.com/atomico";

function component({ name }) {
  return html`<host shadowDom>
      <img src="https://placekitten.com/64">
    </host>`;
}
...
```

## Workaround

Use the [xhtm module](https://github.com/spectjs/xhtm) instead

```jsx
import { h } from "atomico";
import xhtm from "xhtm";
const xhtml = xhtm.bind(h);

function MyComponent() {
  return (
    <host shadowDom>
      {xhtml`<img src="https://placekitten.com/64">`}
    </host>
  );
}
...
```

**Comment by UpperCod** [comment]
Thanks for sharing, I find the use of Range and renderHTML interesting, I'm going to explore more solutions with it
