### ISSUE TITLE
Anyone using atomico with Tailwind CSS?

### ISSUE THREAD

**Issue by shah** [atomicojs/atomico#68]
This is a fascinating library; I've been writing my web components without any frameworks (to eliminate dependencies and stay away from build utilities such as NPM) but love the `atomico` architecture and because it's simple enough to run off of a CDN. 

Has anyone used Tailwind CSS successfully with `atomico`?

**Comment by UpperCod** [comment]
Hi @shah, thanks for starting with Atomico, I have prepared a repository to exemplify the use of Atomico + TailwindCSS, in the example I have configured a Workspace to work with TailwindCSS in an optimal way.

https://github.com/atomicojs/example-tailwindcss

I hope it is useful to you and I invite you to join Discord https://discord.gg/7z3rNhmkNE

**Comment by shah** [comment]
Thanks for the example @UpperCod! I'll try it out and let you know how I fare. I'm trying to keep to using a "zero build tools" (ZBT) strategy (so that non-programmers, e.g., "just designers" feel more comfortable) but with TailwindCSS a ZBT approach may not work.

**Comment by UpperCod** [comment]
TailwindCSS enjoys compilers, personally I don't use it since I like to keep my CSS code as simple as possible ... what would you like to know about zero build tools + Atomico, whether in an example or documentation?...

**Comment by shah** [comment]
Great point @UpperCod - I think Atomico is already ZBT capable (works without NPM) so you "had me at hello" :-).
