### ISSUE TITLE
Examples for use with Deno?

### ISSUE THREAD

**Issue by shah** [atomicojs/atomico#70]
We migrated away from NPM/NodeJS back in 2020 and are very happy with Deno as our replacement TS/JS runtime. Are there any examples available for using Atomico with Deno?

**Comment by UpperCod** [comment]
Not at the moment, since Deno does not recognize document with a global variable.

```bash
  The following options were ignored:
    declaration, emitDeclarationOnly, outDir
error: Uncaught ReferenceError: document is not defined
    at https://cdn.esm.sh/v58/atomico@1.35.0/deno/atomico.js:2:1945
```

If you know a solution to this please tell me.
